export const mockCategories = [
    { id: 1, name: 'Starters', is_active: true },
    { id: 2, name: 'Main Course', is_active: true },
    { id: 3, name: 'Breads', is_active: true },
    { id: 4, name: 'Desserts', is_active: true },
]

export const mockMenuItems = [
    {
        id: '1',
        category_id: 1,
        name: 'Champaran Mutton Handi',
        description: 'Slow-cooked mutton in a clay pot with whole spices and garlic bulbs.',
        price: 450,
        image_url: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60',
        tags: ['Spicy', 'Chef Special'],
        is_available: true,
    },
    {
        id: '2',
        category_id: 1,
        name: 'Roasted Chicken Tikka',
        description: 'Juicy chicken chunks marinated in yogurt and spices, roasted to perfection.',
        price: 320,
        image_url: 'https://images.unsplash.com/photo-1599487488170-dad54fe2480f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60',
        tags: ['Starter'],
        is_available: true,
    },
    {
        id: '3',
        category_id: 2,
        name: 'Ahuna Mutton Curry',
        description: 'Traditional Bihari style mutton curry cooked in mustard oil.',
        price: 480,
        image_url: 'https://images.unsplash.com/photo-1626777552726-4a6b5d29bf9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60',
        tags: ['Gravy'],
        is_available: true,
    },
    {
        id: '4',
        category_id: 3,
        name: 'Butter Naan',
        description: 'Soft and fluffy leavened bread brushed with butter.',
        price: 60,
        image_url: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60',
        tags: ['Veg'],
        is_available: true,
    },
    {
        id: '5',
        category_id: 4,
        name: 'Gulab Jamun',
        description: 'Deep-fried milk solids soaked in rose-flavored sugar syrup.',
        price: 120,
        image_url: 'https://images.unsplash.com/photo-1593701461250-d71f2c2536c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60',
        tags: ['Sweet'],
        is_available: true,
    },
]
